### ISSUE TITLE
Add full ESM support on Node

### ISSUE THREAD

**Issue by flyboarder** [biscuit-auth/biscuit-wasm#4]
The hybrid CJS/ESM package doesn't load on nodejs using native ESM packages and the `--experimental-wasm-modules --experimental-specifier-resolution=node`.

```
import * as wasm from "./biscuit_bg.wasm";
^^^^^^
SyntaxError: Cannot use import statement outside a module
```

**Comment by Geal** [comment]
fixed by #6
